# Generated by Django 2.1.3 on 2019-05-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeapp', '0006_contatct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatct',
            old_name='firstname',
            new_name='firs_tname',
        ),
        migrations.RenameField(
            model_name='contatct',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='contatct',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contatct',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
