# Generated by Django 2.1.3 on 2019-05-03 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeapp', '0007_auto_20190503_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatct',
            old_name='firs_tname',
            new_name='first_name',
        ),
    ]
