# Generated by Django 2.1.3 on 2019-05-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeapp', '0008_auto_20190503_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='introduction',
            field=models.TextField(max_length=200),
        ),
    ]
