# Generated by Django 2.1.3 on 2019-07-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeapp', '0012_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='introduction',
            field=models.TextField(max_length=200),
        ),
    ]
